### PR TITLE
Some desired changes

### PR DESCRIPTION
**Pull request by ayushgoel**
The code here:
1. Solves the bug where the `SAHistoryNavigationViewController` extends behind status bar if a modal `UIViewController` is presented.
2. Removes any custom animation and works purely by following the delegate methods. (IMHO, the animation should be a different pod altogether)
3. Uses some functional constructs where it makes understanding code easier.
4. Extends Sample to present a `UIViewController` modally.

Some of these changes might be in conflict with what you had planned for this pod. In that case, I would like to create a different pod from this.
Also, if you have any suggestions for the code which could make this merge, would love to know them. :innocent:

### CODE REVIEW

**Comment by marty-suzuki** [comment]
Hi @ayushgoel
Sorry for late merging.
Thank you for your pull request!!

**Comment by ayushgoel** [comment]
:+1: When do you plan to do a release for this? :smiley:

**Comment by marty-suzuki** [comment]
i'll release during this week!

**Comment by marty-suzuki** [comment]
released [2.1.0](https://cocoapods.org/pods/SAHistoryNavigationViewController)

**Comment by ayushgoel** [comment]
:cool:

**Pull request merged**
